trigger:
  - master

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-22.04'

variables:
  terraformVersion: '1.11.2'
  workingDirectory: 'Terraform home work 03.04.25'

steps:
  - checkout: self

  - script: |
      echo "Installing Terraform..."
      wget https://releases.hashicorp.com/terraform/${terraformVersion}/terraform_${terraformVersion}_linux_amd64.zip
      unzip terraform_${terraformVersion}_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform --version
    displayName: 'Install Terraform'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'azure-sp-terraform'
      scriptType: bash
      scriptLocation: inlineScript
      workingDirectory: $(workingDirectory)
      inlineScript: |
        echo "Initializing Terraform..."
        terraform init

        echo "Validating Terraform..."
        terraform validate

        if [ "$(Build.Reason)" == "PullRequest" ]; then
          echo "Running Terraform plan on PR..."
          terraform plan -out=tfplan
        elif [ "$(Build.SourceBranch)" == "refs/heads/main" ]; then
          echo "Running Terraform apply on main branch..."
          terraform apply -auto-approve
        fi
    displayName: 'Terraform Init, Validate, Plan/Apply'