trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-22.04'

variables:
  - name: workingDirectory
    value: 'Terraform home work 03.04.25'

  - group: terraform-vars

steps:
  - checkout: self

  - task: DownloadSecureFile@1
    name: downloadTfvars
    inputs:
      secureFile: 'terraform.tfvars'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Init'
    inputs:
      command: 'init'
      workingDirectory: '$(workingDirectory)'
      backendType: 'azurerm'
      backendServiceArm: 'azure-sp-terraform'
      ensureBackend: true

  - task: TerraformTaskV4@4
    displayName: 'Terraform Validate'
    inputs:
      command: 'validate'
      workingDirectory: '$(workingDirectory)'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Plan'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    inputs:
      command: 'plan'
      workingDirectory: '$(workingDirectory)'
      environmentServiceName: 'azure-sp-terraform'
      varFile: '$(downloadTfvars.secureFilePath)'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Apply'
    condition: eq(variables['Build.SourceBranchName'], 'master')
    inputs:
      command: 'apply'
      workingDirectory: '$(workingDirectory)'
      environmentServiceName: 'azure-sp-terraform'
      varFile: '$(downloadTfvars.secureFilePath)'
      args: '-auto-approve'