trigger:
  - master

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-22.04'

variables:
  terraformVersion: '1.5.7'

steps:
  - script: |
      echo "Installing Terraform..."
      wget https://releases.hashicorp.com/terraform/${terraformVersion}/terraform_${terraformVersion}_linux_amd64.zip
      unzip terraform_${terraformVersion}_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform --version
    displayName: 'Install Terraform'

  - checkout: self

  - script: |
      echo "Initializing Terraform..."
      terraform init  
    displayName: 'Terraform Init'
    workingDirectory: 'Terraform home work 03.04.25'

  - script: |
      echo "Validating Terraform configuration..."
      terraform validate
    displayName: 'Terraform Validate'
    workingDirectory: 'Terraform home work 03.04.25'

  - script: |
      echo "Creating Terraform plan..."
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'
    workingDirectory: 'Terraform home work 03.04.25'
    condition: eq(variables['Build.Reason'], 'PullRequest')

  - script: |
      echo "Applying Terraform configuration..."
      terraform apply -auto-approve
    displayName: 'Terraform Apply'
    workingDirectory: 'Terraform home work 03.04.25'
    condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))