trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-22.04'

variables:
  - name: workingDirectory
    value: 'Terraform home work 03.04.25'

  - group: terraform-vars

steps:
  - checkout: self

  - task: DownloadSecureFile@1
    name: downloadTfvars
    inputs:
      secureFile: 'terraform.tfvars'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'azure-sp-terraform'
      backendAzureRmResourceGroupName: 'BeStrong-resource-group'
      backendAzureRmStorageAccountName: 'tfstatebestrong324'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'terraform.tfstate'
      workingDirectory: '$(workingDirectory)'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Validate'
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(workingDirectory)'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Plan'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(workingDirectory)'
      environmentServiceNameAzureRM: 'azure-sp-terraform'

  - task: TerraformTaskV4@4
    displayName: 'Terraform Apply'
    condition: eq(variables['Build.SourceBranchName'], 'master')
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(workingDirectory)'
      environmentServiceNameAzureRM: 'azure-sp-terraform'